
# Sissejuhatus {#intro}

See õpik on kirjutatud inimestele, kes kasutavad, mitte ei uuri, statistikat. 
Õpiku kasutaja peaks olema võimeline töötama R keskkonnas. 
Meie lähenemised statistika õpetamisele on arvutuslikud, mis tähendab, et me eelistame meetodi matemaatilise aluse asemel õpetada selle kasutamist ja tulemuste tõlgendamist. 
See õpik on bayesiaanlik ja ei õpeta sageduslikku statistikat. 
Me usume, et nii on lihtsam ja tulusam statistikat õppida ja et Bayesi statistikat kasutades saab rahuldada 99% teie tegelikest statistilistest vajadustest paremini, kui see on võimalik klassikaliste sageduslike meetoditega. 
Me usume ka, et kuigi praegused kiired arengud bayesi statistikas on tänaseks juba viinud selle suurel määral tavakasutajale kättesaadavasse vormi, toovad lähiaastad selles vallas veel suuri muutusi. 
Nende muutustega koos peab arenema ka bayesi õpetamine. 

Me kasutame järgmisi R-i pakette, mis on kõik loodud bayesi mudelite rakendamise lihtsustamiseks: "rethinking" [@rethinking], "brms" [@brms], "rstanarm" [@rstanarm], "BayesianFirstAid" [@bayesianfirstaid] ja "bayesplot" [@bayesplot]. 
Lisaks veel "bayesboot" bootstrapimiseks [@bayesboot]. 
Bayesi arvutusteks kasutavad need paketid Stan ja JAGS mcmc sämplereid (viimast küll ainult `BayesianFirstAid paket). 
Selle õpiku valmimisel on kasutatud McElreathi [@mcelreath2015], Kruschke [@kruschke2014] ja nn. Gelmani [@gelman2014] õpikuid.

Lugejad, kellele on juba õpetatud sageduslikku statistikat, võivad tahta teada, mille poolest see erineb bayesi statistikast. 
Ehkki me usume, et bayesi statistika õpetamine võrdlevalt sagedusliku statistikaga ei ole parim lahendus, võrdleme lühidalt järgnevalt sageduslikku ja bayesi paradigmasid. 
Kes ei ole õppinud sageduslikku statistikat, võiksid selle osa vahele jätta.
